### ISSUE TITLE
Cant install all required yarn/npm packages

### ISSUE THREAD

**Issue by wloburak** [VisualComposer/vcwb-demo-element-example-plugin#14]
After cloning the repo and 
`yarn install` 
I get following error:
![image](https://user-images.githubusercontent.com/42347719/169893127-65d9d744-eac9-4ec9-b42c-73cd680bc62f.png)

**Comment by nikitahl** [comment]
Hello!

Do you have the latest `git pull` of [vcwb-demo-element-example-plugin](https://github.com/VisualComposer/vcwb-demo-element-example-plugin) repo?

Can you provide an example of your `package.json` file, it looks like there is an issue with postcss-prefix-url package.

**Comment by wloburak** [comment]
Hi Nikita, I have the latest code and I didn't change anything in the package.json file.

`{
  "name": "vcwb",
  "version": "dev",
  "license": "SEE LICENSE IN <https://visualcomposer.com/terms-of-use/>",
  "description": "Visual Composer Website Builder",
  "main": "index.php",
  "repository": {
    "type": "git",
    "url": "git@github.com:Visualcomposer/builder.git"
  },
  "scripts": {
    "standard": "standard --version && standard",
    "build": "webpack --version && webpack --config=./node_modules/vc-webpack-vendors/webpack.config.js",
    "build-production": "webpack --version && webpack --config=./node_modules/vc-webpack-vendors/webpack.config.production.js -p",
    "watch": "webpack --version && webpack --config=./node_modules/vc-webpack-vendors/webpack.config.js --watch"
  },
  "devDependencies": {
    "vc-webpack-vendors": "3.0.5"
  },
  "babel": {
    "presets": [
      "@babel/preset-env",
      "@babel/preset-react"
    ],
    "plugins": [
      "@babel/plugin-transform-runtime",
      "@babel/plugin-proposal-class-properties"
    ]
  },
  "standard": {
    "parser": "babel-eslint",
    "ignore": [
      "public/dist/",
      "tests/",
      "**/public/js"
    ],
    "rules": {
      "jsx-quotes": [
        2,
        "prefer-single"
      ],
      "import/no-webpack-loader-syntax": "off"
    }
  },
  "resolutions": {
    "core-js": "3.18.2",
    "postcss": "8.3.9",
    "css-loader": "6.3.0",
    "color-name": "1.1.4",
    "eslint": "7.32.0",
    "less": "4.1.2",
    "raw-loader": "1.0.0",
    "@babel/runtime": "7.15.4"
  },
  "browserslist": [
    "ie >= 11",
    "last 2 version"
  ]
}
`

This package.json is from here: vcwb-demo-element-example-plugin-master\elements\cssVariablesButton

**Comment by nikitahl** [comment]
Could you also paste the error message text please?

**Comment by wloburak** [comment]
Here's the whole terminal with the error:
`AzureAD+WalterLoburak@DESKTOP-IRUVUNC MINGW64 ~/Downloads/vcwb-demo-element-example-plugin-master/vcwb-demo-element-example-plugin-master/elements/cssVariablesButton
$ yarn install
yarn install v1.22.18
info No lockfile found.
[1/4] Resolving packages...
warning Resolution field "color-name@1.1.4" is incompatible with requested version "color-name@1.1.3"
warning Resolution field "css-loader@6.3.0" is incompatible with requested version "css-loader@6.4.0"
warning vc-webpack-vendors > babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
warning Resolution field "postcss@8.3.9" is incompatible with requested version "postcss@^7.0.6"
warning Resolution field "postcss@8.3.9" is incompatible with requested version "postcss@^6.0.23"
warning Resolution field "postcss@8.3.9" is incompatible with requested version "postcss@^6.x"
warning Resolution field "postcss@8.3.9" is incompatible with requested version "postcss@^5.0.4"
warning Resolution field "postcss@8.3.9" is incompatible with requested version "postcss@^5.0.19"
warning Resolution field "eslint@7.32.0" is incompatible with requested version "eslint@~7.18.0"
warning vc-webpack-vendors > cypress > url > querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
warning vc-webpack-vendors > babel-jest > @jest/transform > jest-haste-map > sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
warning vc-webpack-vendors > babel-jest > @jest/transform > jest-haste-map > sane > micromatch > snapdragon > source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
warning vc-webpack-vendors > babel-jest > @jest/transform > jest-haste-map > sane > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning vc-webpack-vendors > babel-jest > @jest/transform > jest-haste-map > sane > micromatch > snapdragon > source-map-resolve > source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
warning vc-webpack-vendors > babel-jest > @jest/transform > jest-haste-map > sane > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads git://github.com/wpbakery/postcss-functions.git
Directory: C:\Users\WalterLoburak\Downloads\vcwb-demo-element-example-plugin-master\vcwb-demo-element-example-plugin-master\elements\cssVariablesButton
Output:
fatal: unable to connect to github.com:
github.com[0: 140.82.113.4]: errno=Unknown error
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads git://github.com/wpbakery/postcss-prefix-url.git
Directory: C:\Users\WalterLoburak\Downloads\vcwb-demo-element-example-plugin-master\vcwb-demo-element-example-plugin-master\elements\cssVariablesButton
Output:
fatal: unable to connect to github.com:
github.com[0: 140.82.113.4]: errno=Unknown error
    at ProcessTermError.ExtendableBuiltin (C:\Users\WalterLoburak\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:721:66)
    at ProcessTermError.MessageError (C:\Users\WalterLoburak\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:750:123)
    at new ProcessTermError (C:\Users\WalterLoburak\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:790:113)
    at ChildProcess.<anonymous> (C:\Users\WalterLoburak\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:25783:17)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
`

**Comment by nikitahl** [comment]
This is a similar [issue](https://github.com/Polymer/polymer/issues/1468) you can check out.

> The error you report sounds like some kind of connectivity problem with github. If you're behind a proxy, you may get better results by configuring git to use https:// URLs instead of git:// URLs, by running the following command:
> `git config --global url."https://".insteadOf git://`

**Comment by wloburak** [comment]
Hi Nikita, 
Thanks, that helped. 

Question for you, I have a npm installed already in my project, can I use it instead of yarn?
Also, after I run yarn build-production it gives me a following error:
`$ yarn build-production
yarn run v1.22.18
$ webpack --version && webpack --config=./node_modules/vc-webpack-vendors/webpack.config.production.js -p
webpack: 5.58.1
webpack-cli: 4.9.0
webpack-dev-server not installed
[webpack-cli] Error: Unknown option '-p'
`
To fix it you will have to change "-p" in your package.json file to "--mode production" if you're using webpack v4 and up. 
https://github.com/webpack/webpack-cli/issues/1934

**Comment by nikitahl** [comment]
We recommend using `yarn` over `npm`.
To fix this error remove `-p` in the package.json file for the `"build-production"` property (see screenshot). 
We will make a change and create a Pull Request to fix this issue.
![Screenshot 2022-05-27 at 22 25 00](https://user-images.githubusercontent.com/12826823/170777383-8d1b9a57-52f0-40e1-9577-31fef90822ca.png)

**Comment by nikitahl** [comment]
Closing issue:
https://github.com/VisualComposer/vcwb-demo-element-example-plugin/pull/15
